# App Info
ios_app_id                                : #1436810437 #1459479205                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

testflight_link                           : https://testflight.apple.com/join/Cajlhz4X
appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
privacy_link                              : https://marco-leong.com/privacy_memes
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Memes                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Live fast, troll hard.
app_poster                                : assets/screenshot/screenshot1.jpg

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Marco S.I. Leong                                
your_link                                 : https://marco-leong.com/ 
your_city                                 : Sydney                                
email_address                             : marcoleong.developer@gmail.com
facebook_username                         : MarcoLeongDev                                      
instagram_username                        : MarcoLeongDev
twitter_username                          : MarcoLeongDev
github_username                           : MarcoLeongDev
stackoverflow_userid                      : 4972207
youtube_username                          : 






# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Top memes template
    description                           : <image src="assets/features/template.png" width="280"/>
    fontawesome_icon_name                 : cat
    
  - title                                 : Image and text anywhere
    description                           : <image src="assets/features/anywhere.jpg" width="280"/>
    fontawesome_icon_name                 : arrows-alt
  
  - title                                 : Recent image
    description                           : <image src="assets/features/recent.jpg" width="280"/>
    fontawesome_icon_name                 : clock

  - title                                 : Light and Dark mode
    description                           : <image src="assets/features/lightdark.png" width="280"/>
    fontawesome_icon_name                 : adjust

  - title                                 : Textbox always on top
    description                           : <image src="assets/features/textup.png" width="280"/>
    fontawesome_icon_name                 : arrow-up

  - title                                 : Auto trimming
    description                           : <image src="assets/features/autotrim.png" width="280"/>
    fontawesome_icon_name                 : cut

  - title                                 : Remove ads
    description                           : <image src="assets/features/ads.png" width="280"/>
    fontawesome_icon_name                 : times

  - title                                 : Remove watermark
    description                           : <image src="assets/features/watermark.jpg" width="280"/>
    fontawesome_icon_name                 : tint

  - title                                 : Customised Signature
    description                           : <image src="assets/features/signature.jpg" width="280"/>
    fontawesome_icon_name                 : pencil-alt

  - title                                 : Buy me a coffee
    description                           : <image src="assets/features/coffee.jpg" width="280"/>
    fontawesome_icon_name                 : coffee
    
  - title                                 : Statistic
    description                           : <image src="assets/features/stat.jpg" width="280"/>
    fontawesome_icon_name                 : chart-line

  - title                                 : Easter Egg!?
    description                           : ...!?
    fontawesome_icon_name                 : egg


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.75
topbar_title_color                        : "#ffff00"

cover_image                               : assets/headerimage.jpeg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000000"

link_color                                : "#ffff00"

app_title_color                           : "#ffff00"
app_price_color                           : "#ffff00"
app_description_color                     : "#ffff00"

feature_title_color                       : "#ffff00"
feature_text_color                        : "#FCE883"

feature_icons_foreground_color            : "#000000"
feature_icons_background_color            : "#ffff00"

social_icons_foreground_color             : "#000000"
social_icons_background_color             : "#FCE883"

footer_text_color                         : "#FCE883"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
